Develop vertical tweak gitsigns
NTBBloodbath/doom-nvim pull request #132
Opened 2021-09-25 15:33 UTC by osamuaoki

I ported patches from main to devel.

I was surprised normal <C-L> didn't work.  I guess there must be some config parameter somewhere since I sill see the configuration for window jumping.  :-)

2021-09-26 19:06 UTC, NTBBloodbath requested changes
Thank you so much per doing this, I'm really loving all the changes!

Just a small thing to be fixed and we will be ready to go :)

2021-09-26 19:06 UTC, NTBBloodbath commented on lua/doom/core/functions/init.lua
> +    vim.cmd("set expandtab? softtabstop? tabstop? shiftwidth? expandtab?")
Here's a duplicated `expandtab?`

2021-09-27 15:33 UTC, osamuaoki commented
Except for completion, here is my tweak patch and vertical split patch organized in 2 separate series commits.

2021-09-27 16:24 UTC, osamuaoki commented
Oh, your requested change was done.  I did more.  Good night.

2021-09-27 19:36 UTC, NTBBloodbath approved these changes

2021-09-27 19:44 UTC, NTBBloodbath commented
Thank you so much, should I merge this now and add the completion patch later in another PR?

2021-09-28 06:47 UTC, osamuaoki commented
I now see completion may be toggled.  Let me experiment.

2021-09-28 07:07 UTC, osamuaoki commented
Please wait.  Now I know you like these, I realize I need to refine code for multiple use cases.  (For example, depending on package install state, change available tweak option... etc.)

By the way, you make simple merges for these topic branches.  If you use rebase when you pull these topic branches, then logical history is easier to track, I think. 

Also question for topic branch management.  I don't know if you like seeing force updates, squash history, and always rebased branch from the latest develop branch?

In the mean time, I will separate gitsigns patch from this topic branch. That can be merged immediately.

2021-09-28 08:42 UTC, NTBBloodbath commented
> Please wait.  Now I know you like these, I realize I need to refine code for multiple use cases.  (For example, depending on package install state, change available tweak option... etc.)

Sure thing, there's no hurry. It's my time to sleep so take your time haha.

> By the way, you make simple merges for these topic branches.  If you use rebase when you pull these topic branches, then logical history is easier to track, I think. 

Hmm yeah I think you're right. Sometimes I merge or squash but now that you mention this I think rebase could be a better approach for us, especially for retaining a cleaner history and having a more efficient incorporation of the new commits.

> Also question for topic branch management.  I don't know if you like seeing force updates, squash history, and always rebased branch from the latest develop branch?

I'm ok with forced updates if they're necessary and squash history if changes aren't too big so we can have a better tracking of the major changes and rebased branches are also pretty fine.

I think we should maintain a good commits history and rebases are the best approach for this as far as I know.

> In the mean time, I will separate gitsigns patch from this topic branch. That can be merged immediately.

Alright, thank you!

2021-09-28 16:37 UTC, osamuaoki commented
I just pushed a large updates rebased to your latest updated develop branch.

It works for me is the current state.

I think I tested for where autopairs is not installed. I didn't do the same for missing treesetter.    I think this needs to be robust.

I am going to sleep.  So please review and test but don't merge.

Thanks.

2021-09-28 23:24 UTC, NTBBloodbath approved these changes

2021-09-29 00:08 UTC, NTBBloodbath commented
Hi, everything looks _and works_ great on my side.

Thanks for checking the existence of autopairs plugin while testing, as you said this mechanism needs to be robust!

Also thanks for rebasing, hope this is going to be the start of a better commits history :)

2021-09-29 09:42 UTC, osamuaoki commented
Yes, completion toggle is here.

Instead of reading through the code, I cheated by asking the upstream developer to get toggle go with completion.

I also put extra protection for treesetter, too.  Since this is not flag selectable package, it is not conditional in whichkey configuration.  (I am not asking to make such flag in user configuration file.  This topic deserves separate discussion how far should we go to address user modification segregation.  I think current state is healthy.)

Now that I have finished all the desirable features, after cool headed review, this is ready to be merged.

Osamu

2021-09-29 15:09 UTC, osamuaoki commented
If you wants me to rebase, let me now.  (I think it is conflict free rebase.)

2021-09-29 16:13 UTC, NTBBloodbath approved these changes

2021-09-29 16:21 UTC, NTBBloodbath approved these changes

2021-09-29 16:49 UTC, NTBBloodbath commented
> Yes, completion toggle is here.
> 
> Instead of reading through the code, I cheated by asking the upstream developer to get toggle go with completion.

Awesome, nice idea! :+1:

> I also put extra protection for treesetter, too. Since this is not flag selectable package, it is not conditional in whichkey configuration. (I am not asking to make such flag in user configuration file. This topic deserves separate discussion how far should we go to address user modification segregation. I think current state is healthy.)

Yeah we're not able to disable treesitter anymore since a few Doom versions ago, was a "design" choice. I think current protection is enough for us and shouldn't fail.

> Now that I have finished all the desirable features, after cool headed review, this is ready to be merged.
> 
> Osamu

That's great! Thank you so much for this contribution, I really appreciate it :slightly_smiling_face:

2021-09-29 16:50 UTC, NTBBloodbath commented
> If you wants me to rebase, let me now. (I think it is conflict free rebase.)

If this doesn't annoy you then please do it :)

2021-09-30 14:19 UTC, osamuaoki commented
I rebased.  (It was clean automatic rebase)

Please check the last commit which touches your documentation to address things discussed on "issues".

https://github.com/NTBBloodbath/doom-nvim/issues/126

2021-09-30 21:09 UTC, NTBBloodbath approved these changes

2021-09-30 21:10 UTC, NTBBloodbath commented
Thank you so much mate!

2021-09-30 21:10 UTC, merged